# Generated by Django 5.1.5 on 2025-02-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musicalpreference",
            old_name="favorite_genre",
            new_name="artista_favorito",
        ),
        migrations.RenameField(
            model_name="musicalpreference",
            old_name="favorite_artist",
            new_name="cancion_favorita",
        ),
        migrations.RenameField(
            model_name="musicalpreference",
            old_name="favorite_song",
            new_name="genero_favorito",
        ),
    ]
